//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CSS.Sdk.XsdCodeGenerator
//     Date Generated: 2015-07-14 16:24:30
//     XsdCodeGenerator Version: 2.2.108.0
//     .NET Runtime Version: 2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
namespace CSS.Connector.FileProcessing.Parsing.Parser
{
/// <summary>Map between the file type specified in the file name (i.e. 2084) and the full name of the file.</summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XsdCodeGenerator", "Full_2.2.108.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.csssoftware.com/operations/2.0")]
[System.Xml.Serialization.XmlRootAttribute("fileTypeMapConfig", Namespace="http://schemas.csssoftware.com/operations/2.0", IsNullable=false)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.csssoftware.com/operations/2.0")]
public partial class FileTypeMapConfig : CssObject
{
    
    private string _fileType;
    
    /// <summary>Initializes a new instance of FileTypeMapConfig.</summary>
    public FileTypeMapConfig()
    {
    }
    
    /// <summary>The full name of the file being processed, such as "MutualFundNetworkingFile"</summary>
    [System.Xml.Serialization.XmlElementAttribute("fileType")]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string FileType { get; set; }
    
    /// <summary>Determines whether two <b>FileTypeMapConfig</b> objects are equal.</summary>
    ///<param name="obj">The <b>FileTypeMapConfig</b> to compare with the current <b>FileTypeMapConfig</b>.</param>
    ///<returns><b>true</b> if <paramref name="obj"/> is equal to the current <b>FileTypeMapConfig</b>; otherwise <b>false</b>.</returns>
    ///<remarks>This operation checks for value equality.</remarks>
    public override bool Equals(object obj)
    {
        FileTypeMapConfig other = obj as FileTypeMapConfig;
        if ((other != null))
        {
            return this.Equals(other);
        }
        return false;
    }
}
}
