// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the errorMessage in the
// Error List, point to "Suppress Message(s)", and click
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "CSS")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1017:MarkAssembliesWithComVisible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "nrecord", Scope = "resource", Target = "CSS.Operations.FileProcessing.Errors.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "nusing", Scope = "resource", Target = "CSS.Operations.FileProcessing.Errors.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "acats", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.AcatParticipantFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "acatsparticipant", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.AcatParticipantFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "sequencenumber", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.AcatParticipantFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Acats", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.CostBasisInboundReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Isin", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.CostBasisInboundReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Securityissue", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.CostBasisInboundReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Loi", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Priveleges", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Refernece", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Rpo", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Settlingnumberofsubmittingfirm", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "cdsc", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "ein", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "loi", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "mro", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "nav", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "nscc", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "recordtype", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "roa", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "swp", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "tpa", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundNetworkingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Sdr", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.StandardizedDataReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Serv", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.StandardizedDataReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "cdsc", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.StandardizedDataReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "eod", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.StandardizedDataReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "nav", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.StandardizedDataReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "nscc", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.StandardizedDataReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "ssn", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.StandardizedDataReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "str", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.StandardizedDataReportingFileRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "CSS.Operations.FileProcessing.LogicalRecordGroupingHashTable.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Loi", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundPositionFileByCusipRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "loi", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundPositionFileByCusipRegularExpressions.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "tpa", Scope = "resource", Target = "CSS.Operations.FileProcessing.FixedLengthFileResourceFiles.MutualFundPositionFileByCusipRegularExpressions.resources")]