//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Connector.FileProcessing
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSS.Operations.FileProcessing.Inbound.FileWatcher.StringMessages", typeof(StringMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly two rows should be returned from the css_operations_get_folder_names stored procedure which identifies the &apos;in&apos; folder and &apos;processed&apos; folder for this service.	.
        /// </summary>
        internal static string DefTrnError {
            get {
                return ResourceManager.GetString("DefTrnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} process(es) succeeded and {1} failed.  See error log and trade receipt table for full details..
        /// </summary>
        internal static string ErrorInMutlipleProcess {
            get {
                return ResourceManager.GetString("ErrorInMutlipleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error may have occurred moving the file to the processed folder.  View the error table or event log for possible further details.  .
        /// </summary>
        internal static string ErrorMovingFile {
            get {
                return ResourceManager.GetString("ErrorMovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing {0}.  .
        /// </summary>
        internal static string ErrorProcessing {
            get {
                return ResourceManager.GetString("ErrorProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing {0}.  .
        /// </summary>
        internal static string FinishedProcessing {
            get {
                return ResourceManager.GetString("FinishedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the FileDefinition Watcher Service was stopped, the following number of processes were cancelled before completing:  {0}.  To find which processes were affected, look for rows in log_edp before the service was stopped that have a start row and no corresponding end row..
        /// </summary>
        internal static string ProcessingKilledError {
            get {
                return ResourceManager.GetString("ProcessingKilledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following number of processes were cancelled before completing:  {0}.  See error log..
        /// </summary>
        internal static string ProcessingKilledLog {
            get {
                return ResourceManager.GetString("ProcessingKilledLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While processing file {0}, the Program ID to process file of type {1} was not found in def_cmt..
        /// </summary>
        internal static string ProgIdNotFound {
            get {
                return ResourceManager.GetString("ProgIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service starting..
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopping..
        /// </summary>
        internal static string ServiceStopping {
            get {
                return ResourceManager.GetString("ServiceStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to process {0}..
        /// </summary>
        internal static string StartingToProcess {
            get {
                return ResourceManager.GetString("StartingToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the error table or log files for possible further details:  .
        /// </summary>
        internal static string ViewError {
            get {
                return ResourceManager.GetString("ViewError", resourceCulture);
            }
        }
    }
}
