/*====================================================================
NOTE:
This code was auto generated by the FixedLengthFile CSharpCode Generator
This file was created in the directory: 
     C:\TFS\Bronze\Enterprise\CSS\Sdk\Utilities\FixedLengthFile\FlatFileDefinitionFiles\Vanguard
====================================================================*/

using System;
using System.Collections.ObjectModel;
using System.Data;
using System.Linq;
using System.Text.RegularExpressions;

namespace CSS.Connector.FileProcessors.Vanguard.SecurityReport

{

public class SecurityReport : PhysicalRecord
{
public string RecordId { get; set; } // max length 2; required False
public string FileIdentifier { get; set; } // max length 10; required False
public string FileNumber { get; set; } // max length 2; required False
public string DateTimeStamp { get; set; } // max length 26; required False
private DateTime? _dateTimeStampFormatted;
public DateTime DateTimeStampFormatted
{
	get
	{
		if (_dateTimeStampFormatted == null)
		{
			_dateTimeStampFormatted = DateTime.Parse(Formatter.Format(DateTimeStamp, @"(\d{4})-(\d{2})-(\d{2})-(\d{2})\.(\d{2})\.(\d{2})\.(\d{6})~$1/$2/$3T$4:$5:$6.$7~DateTime"));
		}
		return (DateTime)_dateTimeStampFormatted;
	}
}

public BlockingRecord BlockingRecord { get; set; }
}


public class Bank : BlockingRecord
{
public string RecordId { get; set; } // max length 2; required False
public string FileIdentifier { get; set; } // max length 10; required False
public string FileNumber { get; set; } // max length 2; required False
public string BankNumber { get; set; } // max length 5; required False
private int? _bankNumberFormatted;
public int BankNumberFormatted
{
	get
	{
		if (_bankNumberFormatted == null)
		{
			_bankNumberFormatted = int.Parse(Formatter.Format(BankNumber, @"(\d{5})~$1~int"));
		}
		return (int)_bankNumberFormatted;
	}
}

public string BankName { get; set; } // max length 30; required False
public string LoanAmount { get; set; } // max length 18; required False
private Decimal? _loanAmountFormatted;
public Decimal LoanAmountFormatted
{
	get
	{
		if (_loanAmountFormatted == null)
		{
			_loanAmountFormatted = Decimal.Parse(Formatter.Format(LoanAmount, @"([-\d]\d{15})(\d{2})~$1.$2~Decimal"));
		}
		return (Decimal)_loanAmountFormatted;
	}
}

public string CollateralValue { get; set; } // max length 18; required False
private Decimal? _collateralValueFormatted;
public Decimal CollateralValueFormatted
{
	get
	{
		if (_collateralValueFormatted == null)
		{
			_collateralValueFormatted = Decimal.Parse(Formatter.Format(CollateralValue, @"([-\d]\d{15})(\d{2})~$1.$2~Decimal"));
		}
		return (Decimal)_collateralValueFormatted;
	}
}

public string MarketValue { get; set; } // max length 18; required False
private Decimal? _marketValueFormatted;
public Decimal MarketValueFormatted
{
	get
	{
		if (_marketValueFormatted == null)
		{
			_marketValueFormatted = Decimal.Parse(Formatter.Format(MarketValue, @"([-\d]\d{15})(\d{2})~$1.$2~Decimal"));
		}
		return (Decimal)_marketValueFormatted;
	}
}

public Collection<Security> Securities { get; set; }
}


public class Trailer : BlockingRecord
{
public string RecordId { get; set; } // max length 2; required False
public string FileIdentifier { get; set; } // max length 10; required False
public string FileNumber { get; set; } // max length 2; required False
public string NumberOfRecordsInFile { get; set; } // max length 9; required False
private int? _numberOfRecordsInFileFormatted;
public int NumberOfRecordsInFileFormatted
{
	get
	{
		if (_numberOfRecordsInFileFormatted == null)
		{
			_numberOfRecordsInFileFormatted = int.Parse(Formatter.Format(NumberOfRecordsInFile, @"(\d{9})~$1~int"));
		}
		return (int)_numberOfRecordsInFileFormatted;
	}
}

}


public class Security : PhysicalRecord
{
public string RecordId { get; set; } // max length 2; required False
public string FileIdentifier { get; set; } // max length 10; required False
public string FileNumber { get; set; } // max length 2; required False
public string BankNumber { get; set; } // max length 5; required False
private int? _bankNumberFormatted;
public int BankNumberFormatted
{
	get
	{
		if (_bankNumberFormatted == null)
		{
			_bankNumberFormatted = int.Parse(Formatter.Format(BankNumber, @"(\d{5})~$1~int"));
		}
		return (int)_bankNumberFormatted;
	}
}

public string SecurityName { get; set; } // max length 30; required False
public string MarketValue { get; set; } // max length 18; required False
private Decimal? _marketValueFormatted;
public Decimal MarketValueFormatted
{
	get
	{
		if (_marketValueFormatted == null)
		{
			_marketValueFormatted = Decimal.Parse(Formatter.Format(MarketValue, @"([-\d]\d{15})(\d{2})~$1.$2~Decimal"));
		}
		return (Decimal)_marketValueFormatted;
	}
}

public string CollateralValue { get; set; } // max length 18; required False
private Decimal? _collateralValueFormatted;
public Decimal CollateralValueFormatted
{
	get
	{
		if (_collateralValueFormatted == null)
		{
			_collateralValueFormatted = Decimal.Parse(Formatter.Format(CollateralValue, @"([-\d]\d{15})(\d{2})~$1.$2~Decimal"));
		}
		return (Decimal)_collateralValueFormatted;
	}
}

public string Quantity { get; set; } // max length 18; required False
private Decimal? _quantityFormatted;
public Decimal QuantityFormatted
{
	get
	{
		if (_quantityFormatted == null)
		{
			_quantityFormatted = Decimal.Parse(Formatter.Format(Quantity, @"([-\d]\d{12})(\d{5})~$1.$2~Decimal"));
		}
		return (Decimal)_quantityFormatted;
	}
}

public string MarketPrice { get; set; } // max length 18; required False
private Decimal? _marketPriceFormatted;
public Decimal MarketPriceFormatted
{
	get
	{
		if (_marketPriceFormatted == null)
		{
			_marketPriceFormatted = Decimal.Parse(Formatter.Format(MarketPrice, @"([-\d]\d{8})(\d{9})~$1.$2~Decimal"));
		}
		return (Decimal)_marketPriceFormatted;
	}
}

}


[System.Xml.Serialization.XmlInclude(typeof(Bank))]
[System.Xml.Serialization.XmlInclude(typeof(Trailer))]
public class BlockingRecord : PhysicalRecord
{
}

public class PhysicalRecord : object
{
[System.Xml.Serialization.XmlAttribute]
public int PhysicalFileRecordNumber { get; set; }
}

internal static class Formatter
{
	readonly static string codeCharsPositive = "{ABCDEFGHI";
	readonly static string codeCharsNegative = "}JKLMNOPQR";

	internal static string Format(string stringToFormat, string formattingString)
	{
		string outputString = stringToFormat;
		string[] formattingStrings = formattingString.Split('~');
		// formattingStrings should have 3 or 4 components. 3 for dates & 4 for decimalls
		int formattingStringCount = formattingStrings.Count();
		if (formattingStringCount != 3 && formattingStringCount != 4) throw new DataException(string.Format("Formatting string ({0}) is invalid.  It must be tilde delimited with three or four components.  See code for more details.", formattingString));

		if (!Regex.IsMatch(outputString, formattingStrings[0]))
			throw new DataException(string.Format("String to format ({0}) does not match expected format ({1}).", stringToFormat, formattingString));

		outputString = Regex.Replace(outputString, formattingStrings[0], formattingStrings[1]);

		// IBM binary coded decimal where last digit defines least significant digit and sign of the entire number
		if (formattingStrings[2] == "EBCDIC_BCD")
		{
			string rightMostDigit = outputString[outputString.Length - 1].ToString();
			outputString = outputString.Substring(0, outputString.Length - 1);
			int index = codeCharsNegative.IndexOf(rightMostDigit);
			if (index > -1)
			{
				outputString = "-" + outputString + index.ToString();
			}
			else
				outputString += codeCharsPositive.IndexOf(rightMostDigit).ToString();
			formattingStrings[2] = "Decimal"; // Once data has been fixed, it's a normal decimal
		}

		if (formattingStringCount == 4)
		{
			TypeCode typeCode = (TypeCode)Enum.Parse(typeof(TypeCode), formattingStrings[2], true);
			outputString = string.Format(formattingStrings[3], Convert.ChangeType(outputString, typeCode));
		}
		return outputString;
	}
}
}
